from formalgeo import GeometricConfiguration
from formalgeo import load_json, parse_gdl, debug_execute
from func_timeout import func_timeout, FunctionTimedOut
import time


def construction(timing=False):
    """constructions: 42"""
    gc = GeometricConfiguration(parsed_gdl=parse_gdl(load_json('gdl.json')))

    start_time = time.time()

    debug_execute(gc.construct, ['Circle(Γ)&Circle(Ω):IntersectBetweenCircle(Ω,Γ)&G(Sub(Γ.rc,Ω.rc))', 19])
    debug_execute(gc.construct, ['Point(M):CenterOfCircle(M,Ω)'])
    debug_execute(gc.construct, ['Point(N):CenterOfCircle(N,Γ)'])
    debug_execute(gc.construct, ['Point(A):PointOnCircle(A,Ω)&PointOnCircle(A,Γ)&PointLeftSegment(A,N,M)'])
    debug_execute(gc.construct, ['Point(B):PointOnCircle(B,Ω)&PointOnCircle(B,Γ)&PointLeftSegment(B,M,N)'])
    debug_execute(gc.construct, ['Line(a):PointOnLine(M,a)&PointOnLine(N,a)'])
    debug_execute(gc.construct, ['Point(C):PointOnLine(C,a)&PointOnCircle(C,Ω)&PointLeftSegment(C,A,B)'])
    debug_execute(gc.construct, ['Point(D):PointOnLine(D,a)&PointOnCircle(D,Γ)&PointLeftSegment(D,B,A)'])
    debug_execute(gc.construct, ['Line(c):PointOnLine(A,c)&PointOnLine(D,c)'])
    debug_execute(gc.construct, ['Line(d):PointOnLine(A,d)&PointOnLine(C,d)'])
    debug_execute(gc.construct, ['Point(P):CircumcenterOfTriangle(P,C,d,A,c,D,a)'])
    debug_execute(gc.construct, ['Line(p):PointOnLine(A,p)&PointOnLine(P,p)'])
    debug_execute(gc.construct, ['Point(E):PointOnLine(E,p)&PointOnCircle(E,Ω)&~SamePoint(E,A)'])
    debug_execute(gc.construct, ['Point(F):PointOnLine(F,p)&PointOnCircle(F,Γ)&~SamePoint(F,A)'])
    debug_execute(gc.construct, ['Line(n):PointOnLine(P,n)&PointOnLine(M,n)'])
    debug_execute(gc.construct, ['Line(m):PointOnLine(P,m)&PointOnLine(N,m)'])
    debug_execute(gc.construct, ['Point(H):OrthocenterOfTriangle(H,P,n,M,a,N,m)'])
    debug_execute(gc.construct, ['Line(f):PointOnLine(B,f)&PointOnLine(E,f)'])
    debug_execute(gc.construct, ['Line(e):PointOnLine(B,e)&PointOnLine(F,e)'])
    debug_execute(gc.construct, ['Circle(Φ):CircumcircleOfTriangle(Φ,B,f,E,p,F,e)'])

    debug_execute(gc.construct, ['Line(x):PointOnLine(M,x)&PointOnLine(E,x)'])  # aux
    debug_execute(gc.construct, ['Line(y):PointOnLine(N,y)&PointOnLine(F,y)'])
    debug_execute(gc.construct, ['Point(T):PointOnLine(T,x)&PointOnLine(T,y)'])
    debug_execute(gc.construct, ['Line(t):PointOnLine(H,t)&PointOnLine(T,t)'])
    debug_execute(gc.construct, ['Circle(Δ):CircumcircleOfTriangle(Δ,C,d,A,c,D,a)'])
    debug_execute(gc.construct, ['Line(g):PointOnLine(P,g)&PointOnLine(C,g)'])
    debug_execute(gc.construct, ['Line(h):PointOnLine(P,h)&PointOnLine(D,h)'])
    debug_execute(gc.construct, ['Line(i):PointOnLine(M,i)&PointOnLine(H,i)'])
    debug_execute(gc.construct, ['Line(j):PointOnLine(N,j)&PointOnLine(H,j)'])
    debug_execute(gc.construct, ['Line(k):PointOnLine(A,k)&PointOnLine(M,k)'])
    debug_execute(gc.construct, ['Line(l):PointOnLine(A,l)&PointOnLine(N,l)'])
    debug_execute(gc.construct, ['Line(u):PointOnLine(B,u)&PointOnLine(C,u)'])
    debug_execute(gc.construct, ['Line(v):PointOnLine(A,v)&PointOnLine(B,v)'])
    debug_execute(gc.construct, ['Line(w):PointOnLine(B,w)&PointOnLine(D,w)'])
    debug_execute(gc.construct, ['Point(X):PointOnLine(X,n)&PointOnLine(X,d)'])
    debug_execute(gc.construct, ['Point(Y):PointOnLine(Y,m)&PointOnLine(Y,c)'])
    debug_execute(gc.construct, ['Point(G):CenterOfCircle(G,Φ)'])
    debug_execute(gc.construct, ['Line(b):PointOnLine(T,b)&PointOnLine(G,b)'])
    debug_execute(gc.construct, ['Point(Q):PointOnLine(Q,p)&PointOnLine(Q,b)'])
    debug_execute(gc.construct, ['Line(q):PointOnLine(F,q)&PointOnLine(G,q)'])
    debug_execute(gc.construct, ['Line(o):PointOnLine(E,o)&PointOnLine(G,o)'])
    debug_execute(gc.construct, ['Point(K):PointOnLine(K,v)&PointOnLine(K,a)'])

    debug_execute(gc.set_goal, ['ParallelBetweenLine(p,t)&TangentBetweenLineAndCircle(t,Φ)'])

    end_time = time.time()

    if not timing:
        gc.draw_gc(scale=2, save_path='../outputs/', file_format='png')

    return gc, end_time - start_time


def forward_solving_interactive(timing=False):
    """theorems: 204"""
    gc, _ = construction(timing)

    start_time = time.time()

    # common sense
    debug_execute(gc.apply, ['circumcenter_of_triangle_property_center_of_circle(P,Δ,C,d,A,c,D,a)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_multiple_forms(Δ,C,d,A,c,D,a)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_multiple_forms(Δ,A,c,D,a,C,d)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle(Δ,A,c,D,a,C,d)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle(Δ,D,a,C,d,A,c)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle(Δ,C,d,A,c,D,a)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Δ,P,C)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Δ,P,A)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Δ,P,D)'])

    # prove ∠gd = ∠dp
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(P,C,P,A)'])
    debug_execute(gc.apply, ['triangle_determination(P,g,C,d,A,p)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(P,g,C,d,A,p)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(P,g,C,d,A,p)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(g,d,d,p)'])

    # prove ∠pc = ∠ch
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(P,A,P,D)'])
    debug_execute(gc.apply, ['triangle_determination(P,p,A,c,D,h)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(P,p,A,c,D,h)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(P,p,A,c,D,h)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(p,c,c,h)'])

    # prove ∠ga = ∠ah
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(P,C,P,D)'])
    debug_execute(gc.apply, ['triangle_determination(P,g,C,a,D,h)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(P,g,C,a,D,h)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(P,g,C,a,D,h)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(g,a,a,h)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Ω,M,C)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Ω,M,A)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Ω,M,E)'])

    # prove ∠ad = ∠dk
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(M,C,M,A)'])
    debug_execute(gc.apply, ['triangle_determination(M,a,C,d,A,k)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(M,a,C,d,A,k)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(M,a,C,d,A,k)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(a,d,d,k)'])

    # prove ∠kp = ∠px
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(M,A,M,E)'])
    debug_execute(gc.apply, ['triangle_determination(M,k,A,p,E,x)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(M,k,A,p,E,x)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(M,k,A,p,E,x)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(k,p,p,x)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Γ,N,A)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Γ,N,D)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Γ,N,F)'])

    # prove ∠lc = ∠ca
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(N,A,N,D)'])
    debug_execute(gc.apply, ['triangle_determination(N,l,A,c,D,a)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(N,l,A,c,D,a)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(N,l,A,c,D,a)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(l,c,c,a)'])

    # prove ∠yp = ∠pl
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(N,F,N,A)'])
    debug_execute(gc.apply, ['triangle_determination(N,y,F,p,A,l)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(N,y,F,p,A,l)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(N,y,F,p,A,l)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(y,p,p,l)'])
    debug_execute(gc.apply, ['line_property_angle_addition(C,g,a,d)'])
    debug_execute(gc.apply, ['line_property_angle_addition(A,d,k,p)'])
    debug_execute(gc.apply, ['line_property_angle_addition(A,p,l,c)'])
    debug_execute(gc.apply, ['line_property_angle_addition(D,c,a,h)'])

    # prove y // k
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(y,p,k,p)'])
    debug_execute(gc.apply, ['parallel_determination_angle_equal(y,k,p)'])

    # prove x // l
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(p,x)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(p,l)'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(x,p,l,p)'])
    debug_execute(gc.apply, ['parallel_determination_angle_equal(x,l,p)'])
    debug_execute(gc.apply, ['perpendicular_bisector_determination_center_line_and_common_chord(Ω,Γ,M,N,a,A,B,v)'])
    debug_execute(gc.apply, ['perpendicular_bisector_property_perpendicular_between_line(a,v,A,B)'])

    # prove ∠fp = 2∠ad
    debug_execute(gc.apply, ['perpendicular_between_line_property_multiple_forms(a,v)'])
    debug_execute(gc.apply, ['perpendicular_between_line_property_angle(a,v)'])
    debug_execute(gc.apply, ['perpendicular_between_line_property_angle(v,a)'])
    debug_execute(gc.apply, ['perpendicular_bisector_property_distance_equal(a,v,A,B,C)'])
    debug_execute(gc.apply, ['triangle_determination(C,d,A,v,B,u)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(C,d,A,v,B,u)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(C,d,A,v,B,u)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(d,v,v,u)'])
    debug_execute(gc.apply, ['triangle_determination(A,v,K,a,C,d)'])
    debug_execute(gc.apply, ['triangle_determination(B,u,C,a,K,v)'])
    debug_execute(gc.apply, ['triangle_property_angle_sum(A,v,K,a,C,d)'])
    debug_execute(gc.apply, ['triangle_property_angle_sum(B,u,C,a,K,v)'])
    debug_execute(gc.apply, ['line_property_angle_addition(C,u,a,d)'])
    debug_execute(gc.apply, ['concyclic_between_points_determination_same_circle(Ω,B,C,A,E)'])
    debug_execute(gc.apply, ['concyclic_between_points_property_inscribed_angle_sum(B,u,C,d,A,p,E,f)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(p,f)'])

    # prove ∠pe = 2∠ca
    debug_execute(gc.apply, ['perpendicular_bisector_property_multiple_forms(a,v,A,B)'])
    debug_execute(gc.apply, ['perpendicular_bisector_property_distance_equal(a,v,B,A,D)'])
    debug_execute(gc.apply, ['triangle_determination(D,w,B,v,A,c)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(D,w,B,v,A,c)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(D,w,B,v,A,c)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(w,v,v,c)'])
    debug_execute(gc.apply, ['triangle_determination(D,w,B,v,K,a)'])
    debug_execute(gc.apply, ['triangle_determination(D,a,K,v,A,c)'])
    debug_execute(gc.apply, ['triangle_property_angle_sum(D,w,B,v,K,a)'])
    debug_execute(gc.apply, ['triangle_property_angle_sum(D,a,K,v,A,c)'])
    debug_execute(gc.apply, ['line_property_angle_addition(D,c,a,w)'])
    debug_execute(gc.apply, ['concyclic_between_points_determination_same_circle(Γ,B,A,D,F)'])
    debug_execute(gc.apply, ['concyclic_between_points_property_inscribed_angle_equal(B,w,A,c,D,e,F,p)'])

    # prove ∠ay = 2∠ad
    debug_execute(gc.apply, ['triangle_property_angle_sum(M,a,C,d,A,k)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(a,k)'])
    debug_execute(gc.apply, ['parallel_property_angle_equal(y,k,a)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(y,a,k,a)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(a,y)'])

    # prove ∠la = 2∠ca
    debug_execute(gc.apply, ['triangle_property_angle_sum(N,l,A,c,D,a)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(a,l)'])

    # prove ∠xy = 2∠ad + 2∠ca
    debug_execute(gc.apply, ['line_property_angle_addition(N,l,a,y)'])
    debug_execute(gc.apply, ['parallel_property_multiple_forms(x,l)'])
    debug_execute(gc.apply, ['parallel_property_angle_equal(l,x,y)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(l,y,x,y)'])

    # prove ∠ef + ∠xy = 180° (T on Φ)
    debug_execute(gc.apply, ['triangle_determination(F,e,B,f,E,p)'])
    debug_execute(gc.apply, ['triangle_property_angle_sum(F,e,B,f,E,p)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_multiple_forms(Φ,B,f,E,p,F,e)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_multiple_forms(Φ,E,p,F,e,B,f)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle(Φ,B,f,E,p,F,e)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle(Φ,E,p,F,e,B,f)'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle(Φ,F,e,B,f,E,p)'])
    debug_execute(gc.apply, ['concyclic_between_points_determination_inscribed_angle_sum(F,e,B,f,E,x,T,y)'])
    debug_execute(gc.apply, ['point_on_circle_determination_concyclic(Φ,F,B,E,T)'])

    # prove m ⊥ c
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(N,P,N,P)'])
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(A,N,D,N)'])
    debug_execute(gc.apply, ['triangle_determination(A,l,N,m,P,p)'])
    debug_execute(gc.apply, ['triangle_determination(D,h,P,m,N,a)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_determination_sss(A,l,N,m,P,p,D,a,N,m,P,h)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_angle_equal(A,l,N,m,P,p,D,a,N,m,P,h)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(l,m,m,a)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(l,m)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(m,a)'])
    debug_execute(gc.apply, ['triangle_determination(Y,m,N,l,A,c)'])
    debug_execute(gc.apply, ['triangle_determination(Y,c,D,a,N,m)'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(m,l,a,m)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_determination_asa(Y,m,N,l,A,c,Y,m,N,a,D,c)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_multiple_forms(Y,m,N,l,A,c,Y,m,N,a,D,c)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_multiple_forms(N,l,A,c,Y,m,N,a,D,c,Y,m)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_angle_equal(A,c,Y,m,N,l,D,c,Y,m,N,a)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(c,m,m,c)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(m,c)'])

    # prove n ⊥ d
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(C,M,A,M)'])
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(M,P,M,P)'])
    debug_execute(gc.apply, ['triangle_determination(C,a,M,n,P,g)'])
    debug_execute(gc.apply, ['triangle_determination(A,p,P,n,M,k)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_determination_sss(C,a,M,n,P,g,A,k,M,n,P,p)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_angle_equal(C,a,M,n,P,g,A,k,M,n,P,p)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(a,n,n,k)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(a,n)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(n,k)'])
    debug_execute(gc.apply, ['triangle_determination(X,n,M,a,C,d)'])
    debug_execute(gc.apply, ['triangle_determination(X,d,A,k,M,n)'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(n,a,k,n)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_determination_asa(X,n,M,a,C,d,X,n,M,k,A,d)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_multiple_forms(X,n,M,a,C,d,X,n,M,k,A,d)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_multiple_forms(M,a,C,d,X,n,M,k,A,d,X,n)'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_angle_equal(C,d,X,n,M,a,A,d,X,n,M,k)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(d,n,n,d)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(n,d)'])

    # prove i // c
    debug_execute(gc.apply, ['orthocenter_of_triangle_property_multiple_forms(H,P,n,M,a,N,m)'])
    debug_execute(gc.apply, ['orthocenter_of_triangle_property_perpendicular(H,i,M,a,N,m,P,n)'])
    debug_execute(gc.apply, ['perpendicular_between_line_property_angle(i,m)'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(i,m,c,m)'])
    debug_execute(gc.apply, ['parallel_determination_angle_equal(i,c,m)'])

    # prove ∠xi = ∠ia
    debug_execute(gc.apply, ['parallel_property_angle_equal(i,c,a)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(i,a,c,a)'])
    debug_execute(gc.apply, ['line_property_angle_addition(M,x,i,a)'])
    debug_execute(gc.apply, ['parallel_property_angle_equal(x,l,a)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(x,a,l,a)'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(x,i,i,a)'])
    debug_execute(gc.apply, ['angle_bisector_determination_angle_equal(M,i,x,a)'])

    # prove j // d
    debug_execute(gc.apply, ['orthocenter_of_triangle_property_multiple_forms(H,M,a,N,m,P,n)'])
    debug_execute(gc.apply, ['orthocenter_of_triangle_property_perpendicular(H,j,N,m,P,n,M,a)'])
    debug_execute(gc.apply, ['perpendicular_between_line_property_angle(j,n)'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(d,n,j,n)'])
    debug_execute(gc.apply, ['parallel_determination_angle_equal(d,j,n)'])

    # prove ∠aj = ∠jy
    debug_execute(gc.apply, ['parallel_property_angle_equal(d,j,a)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(d,a,j,a)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(a,d)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(a,j)'])
    debug_execute(gc.apply, ['line_property_angle_addition(N,a,j,y)'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(a,j,j,y)'])
    debug_execute(gc.apply, ['angle_bisector_determination_angle_equal(N,j,a,y)'])

    # prove ∠yt = ∠tx
    debug_execute(gc.apply, ['triangle_determination(T,x,M,a,N,y)'])
    debug_execute(gc.apply, ['incenter_of_triangle_determination_angle_bisector(H,i,j,T,x,M,a,N,y)'])
    debug_execute(gc.apply, ['incenter_of_triangle_property_angle_bisector(H,t,T,x,M,a,N,y)'])
    debug_execute(gc.apply, ['angle_bisector_property_equal_angle(T,t,y,x)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(y,t,t,x)'])

    # prove t // p
    debug_execute(gc.apply, ['line_property_angle_addition(T,y,t,x)'])
    debug_execute(gc.apply, ['triangle_determination(F,p,E,x,T,y)'])
    debug_execute(gc.apply, ['triangle_property_angle_sum(F,p,E,x,T,y)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(y,x)'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic(t,x,p,x)'])
    debug_execute(gc.apply, ['parallel_determination_angle_equal(t,p,x)'])
    debug_execute(gc.apply, ['parallel_property_multiple_forms(t,p)'])

    # prove b ⊥ p
    debug_execute(gc.apply, ['triangle_determination(G,q,F,p,Q,b)'])
    debug_execute(gc.apply, ['triangle_determination(G,b,Q,p,E,o)'])
    debug_execute(gc.apply, ['triangle_determination(G,q,F,p,E,o)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Φ,G,F)'])
    debug_execute(gc.apply, ['circle_property_radius_equal(Φ,G,E)'])
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic(G,F,G,E)'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal(G,q,F,p,E,o)'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal(G,q,F,p,E,o)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(q,p,p,o)'])
    debug_execute(gc.apply, ['arc_property_central_angle_and_inscribed_angle(Φ,G,T,F,E,b,q,x,p)'])
    debug_execute(gc.apply, ['arc_property_central_angle_and_inscribed_angle(Φ,G,E,T,F,o,b,p,y)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(b,o)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(q,b)'])
    debug_execute(gc.apply, ['triangle_property_angle_sum(G,q,F,p,Q,b)'])
    debug_execute(gc.apply, ['triangle_property_angle_sum(G,b,Q,p,E,o)'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle(p,b)'])
    debug_execute(gc.apply, ['parallel_property_angle_equal(t,p,b)'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic(t,b,p,b)'])

    # prove t ⊥ p
    debug_execute(gc.apply, ['perpendicular_between_line_determination_angle(t,b)'])
    debug_execute(gc.apply, ['perpendicular_between_line_property_multiple_forms(t,b)'])
    debug_execute(gc.apply, ['tangent_between_line_and_circle_determination_perpendicular(Φ,G,b,T,t)'])

    end_time = time.time()

    if not timing:
        gc.show_gc()
        print(gc.get_gc())
        gc.draw_sg(save_path='../outputs/', file_format='png')

    return gc, end_time - start_time


def backward_solving_interactive(timing=False):
    """theorems: 204"""
    gc, _ = construction(timing)

    start_time = time.time()

    debug_execute(gc.decompose, ['tangent_between_line_and_circle_determination_perpendicular(Φ,G,b,T,t)'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_multiple_forms(t,b)'])
    debug_execute(gc.decompose, ['perpendicular_between_line_determination_angle(t,b)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(t,b,p,b)'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal(t,p,b)'])
    debug_execute(gc.decompose, ['parallel_property_multiple_forms(t,p)'])
    debug_execute(gc.decompose, ['parallel_determination_angle_equal(t,p,x)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(t,x,p,x)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(F,p,E,x,T,y)'])
    debug_execute(gc.decompose, ['triangle_determination(F,p,E,x,T,y)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(T,y,t,x)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(y,t,t,x)'])
    debug_execute(gc.decompose, ['angle_bisector_property_equal_angle(T,t,y,x)'])
    debug_execute(gc.decompose, ['incenter_of_triangle_property_angle_bisector(H,t,T,x,M,a,N,y)'])
    debug_execute(gc.decompose, ['incenter_of_triangle_determination_angle_bisector(H,i,j,T,x,M,a,N,y)'])
    debug_execute(gc.decompose, ['triangle_determination(T,x,M,a,N,y)'])
    debug_execute(gc.decompose, ['angle_bisector_determination_angle_equal(N,j,a,y)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(a,j,j,y)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(N,a,j,y)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(a,j)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(d,a,j,a)'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal(d,j,a)'])
    debug_execute(gc.decompose, ['parallel_determination_angle_equal(d,j,n)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(d,n,j,n)'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_angle(j,n)'])
    debug_execute(gc.decompose, ['orthocenter_of_triangle_property_perpendicular(H,j,N,m,P,n,M,a)'])
    debug_execute(gc.decompose, ['orthocenter_of_triangle_property_multiple_forms(H,M,a,N,m,P,n)'])
    debug_execute(gc.decompose, ['angle_bisector_determination_angle_equal(M,i,x,a)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(x,i,i,a)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(M,x,i,a)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(i,a,c,a)'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal(i,c,a)'])
    debug_execute(gc.decompose, ['parallel_determination_angle_equal(i,c,m)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(i,m,c,m)'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_angle(i,m)'])
    debug_execute(gc.decompose, ['orthocenter_of_triangle_property_perpendicular(H,i,M,a,N,m,P,n)'])
    debug_execute(gc.decompose, ['orthocenter_of_triangle_property_multiple_forms(H,P,n,M,a,N,m)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(n,d)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(d,n,n,d)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_angle_equal(C,d,X,n,M,a,A,d,X,n,M,k)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_multiple_forms(M,a,C,d,X,n,M,k,A,d,X,n)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_multiple_forms(X,n,M,a,C,d,X,n,M,k,A,d)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_determination_asa(X,n,M,a,C,d,X,n,M,k,A,d)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(n,a,k,n)'])
    debug_execute(gc.decompose, ['triangle_determination(X,d,A,k,M,n)'])
    debug_execute(gc.decompose, ['triangle_determination(X,n,M,a,C,d)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(n,k)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(a,n)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(a,n,n,k)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_angle_equal(C,a,M,n,P,g,A,k,M,n,P,p)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_determination_sss(C,a,M,n,P,g,A,k,M,n,P,p)'])
    debug_execute(gc.decompose, ['triangle_determination(A,p,P,n,M,k)'])
    debug_execute(gc.decompose, ['triangle_determination(C,a,M,n,P,g)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(M,P,M,P)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(C,M,A,M)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(m,c)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(c,m,m,c)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_angle_equal(A,c,Y,m,N,l,D,c,Y,m,N,a)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_multiple_forms(N,l,A,c,Y,m,N,a,D,c,Y,m)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_multiple_forms(Y,m,N,l,A,c,Y,m,N,a,D,c)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_determination_asa(Y,m,N,l,A,c,Y,m,N,a,D,c)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(m,l,a,m)'])
    debug_execute(gc.decompose, ['triangle_determination(Y,c,D,a,N,m)'])
    debug_execute(gc.decompose, ['triangle_determination(Y,m,N,l,A,c)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(m,a)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(l,m)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(l,m,m,a)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_angle_equal(A,l,N,m,P,p,D,a,N,m,P,h)'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_determination_sss(A,l,N,m,P,p,D,a,N,m,P,h)'])
    debug_execute(gc.decompose, ['triangle_determination(D,h,P,m,N,a)'])
    debug_execute(gc.decompose, ['triangle_determination(A,l,N,m,P,p)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(A,N,D,N)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(N,P,N,P)'])
    debug_execute(gc.decompose, ['point_on_circle_determination_concyclic(Φ,F,B,E,T)'])
    debug_execute(gc.decompose, ['concyclic_between_points_determination_inscribed_angle_sum(F,e,B,f,E,x,T,y)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle(Φ,F,e,B,f,E,p)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle(Φ,E,p,F,e,B,f)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle(Φ,B,f,E,p,F,e)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_multiple_forms(Φ,E,p,F,e,B,f)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_multiple_forms(Φ,B,f,E,p,F,e)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(F,e,B,f,E,p)'])
    debug_execute(gc.decompose, ['triangle_determination(F,e,B,f,E,p)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(l,y,x,y)'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal(l,x,y)'])
    debug_execute(gc.decompose, ['parallel_property_multiple_forms(x,l)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(N,l,a,y)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(a,l)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(N,l,A,c,D,a)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(a,y)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(y,a,k,a)'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal(y,k,a)'])
    debug_execute(gc.decompose, ['concyclic_between_points_property_inscribed_angle_equal(B,w,A,c,D,e,F,p)'])
    debug_execute(gc.decompose, ['concyclic_between_points_determination_same_circle(Γ,B,A,D,F)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(D,c,a,w)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(D,a,K,v,A,c)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(D,w,B,v,K,a)'])
    debug_execute(gc.decompose, ['triangle_determination(D,a,K,v,A,c)'])
    debug_execute(gc.decompose, ['triangle_determination(D,w,B,v,K,a)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(w,v,v,c)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(D,w,B,v,A,c)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(D,w,B,v,A,c)'])
    debug_execute(gc.decompose, ['triangle_determination(D,w,B,v,A,c)'])
    debug_execute(gc.decompose, ['perpendicular_bisector_property_distance_equal(a,v,B,A,D)'])
    debug_execute(gc.decompose, ['perpendicular_bisector_property_multiple_forms(a,v,A,B)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(p,f)'])
    debug_execute(gc.decompose, ['concyclic_between_points_property_inscribed_angle_sum(B,u,C,d,A,p,E,f)'])
    debug_execute(gc.decompose, ['concyclic_between_points_determination_same_circle(Ω,B,C,A,E)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(C,u,a,d)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(B,u,C,a,K,v)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(A,v,K,a,C,d)'])
    debug_execute(gc.decompose, ['triangle_determination(B,u,C,a,K,v)'])
    debug_execute(gc.decompose, ['triangle_determination(A,v,K,a,C,d)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(d,v,v,u)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(C,d,A,v,B,u)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(C,d,A,v,B,u)'])
    debug_execute(gc.decompose, ['triangle_determination(C,d,A,v,B,u)'])
    debug_execute(gc.decompose, ['perpendicular_bisector_property_distance_equal(a,v,A,B,C)'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_angle(v,a)'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_angle(a,v)'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_multiple_forms(a,v)'])
    debug_execute(gc.decompose, ['perpendicular_bisector_property_perpendicular_between_line(a,v,A,B)'])
    debug_execute(gc.decompose, ['perpendicular_bisector_determination_center_line_and_common_chord(Ω,Γ,M,N,a,A,B,v)'])
    debug_execute(gc.decompose, ['parallel_determination_angle_equal(x,l,p)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(x,p,l,p)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(p,l)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(p,x)'])
    debug_execute(gc.decompose, ['parallel_determination_angle_equal(y,k,p)'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic(y,p,k,p)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(D,c,a,h)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(A,p,l,c)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(A,d,k,p)'])
    debug_execute(gc.decompose, ['line_property_angle_addition(C,g,a,d)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(y,p,p,l)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(N,y,F,p,A,l)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(N,y,F,p,A,l)'])
    debug_execute(gc.decompose, ['triangle_determination(N,y,F,p,A,l)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(N,F,N,A)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(l,c,c,a)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(N,l,A,c,D,a)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(N,l,A,c,D,a)'])
    debug_execute(gc.decompose, ['triangle_determination(N,l,A,c,D,a)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(N,A,N,D)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Γ,N,F)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Γ,N,D)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Γ,N,A)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(k,p,p,x)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(M,k,A,p,E,x)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(M,k,A,p,E,x)'])
    debug_execute(gc.decompose, ['triangle_determination(M,k,A,p,E,x)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(M,A,M,E)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(a,d,d,k)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(M,a,C,d,A,k)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(M,a,C,d,A,k)'])
    debug_execute(gc.decompose, ['triangle_determination(M,a,C,d,A,k)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(M,C,M,A)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Ω,M,E)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Ω,M,A)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Ω,M,C)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(g,a,a,h)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(P,g,C,a,D,h)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(P,g,C,a,D,h)'])
    debug_execute(gc.decompose, ['triangle_determination(P,g,C,a,D,h)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(P,C,P,D)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(p,c,c,h)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(P,p,A,c,D,h)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(P,p,A,c,D,h)'])
    debug_execute(gc.decompose, ['triangle_determination(P,p,A,c,D,h)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(P,A,P,D)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(g,d,d,p)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(P,g,C,d,A,p)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(P,g,C,d,A,p)'])
    debug_execute(gc.decompose, ['triangle_determination(P,g,C,d,A,p)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(P,C,P,A)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Δ,P,D)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Δ,P,A)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Δ,P,C)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle(Δ,C,d,A,c,D,a)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle(Δ,D,a,C,d,A,c)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle(Δ,A,c,D,a,C,d)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_multiple_forms(Δ,A,c,D,a,C,d)'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_multiple_forms(Δ,C,d,A,c,D,a)'])
    debug_execute(gc.decompose, ['circumcenter_of_triangle_property_center_of_circle(P,Δ,C,d,A,c,D,a)'])
    debug_execute(gc.decompose, ['arc_property_central_angle_and_inscribed_angle(Φ,G,E,T,F,o,b,p,y)'])
    debug_execute(gc.decompose, ['arc_property_central_angle_and_inscribed_angle(Φ,G,T,F,E,b,q,x,p)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(y,x)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(a,d)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(x,a,l,a)'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal(x,l,a)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(a,k)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(M,a,C,d,A,k)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(p,b)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(G,b,Q,p,E,o)'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum(G,q,F,p,Q,b)'])
    debug_execute(gc.decompose, ['triangle_determination(G,b,Q,p,E,o)'])
    debug_execute(gc.decompose, ['triangle_determination(G,q,F,p,Q,b)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(q,b)'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle(b,o)'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic(q,p,p,o)'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal(G,q,F,p,E,o)'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal(G,q,F,p,E,o)'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic(G,F,G,E)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Φ,G,E)'])
    debug_execute(gc.decompose, ['circle_property_radius_equal(Φ,G,F)'])
    debug_execute(gc.decompose, ['triangle_determination(G,q,F,p,E,o)'])

    end_time = time.time()

    if not timing:
        gc.show_gc()
        print(gc.get_gc())
        gc.draw_sg(save_path='../outputs/', file_format='png')

    return gc, end_time - start_time


def forward_solving_automatic(timing=False):
    """theorems: 204"""
    gc, _ = construction(timing)

    start_time = time.time()

    # common sense
    debug_execute(gc.apply, ['circumcenter_of_triangle_property_center_of_circle'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_multiple_forms'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_multiple_forms'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle'])
    debug_execute(gc.apply, ['circle_property_radius_equal'])
    debug_execute(gc.apply, ['circle_property_radius_equal'])
    debug_execute(gc.apply, ['circle_property_radius_equal'])

    # prove ∠gd = ∠dp
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])

    # prove ∠pc = ∠ch
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])

    # prove ∠ga = ∠ah
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])
    debug_execute(gc.apply, ['circle_property_radius_equal'])
    debug_execute(gc.apply, ['circle_property_radius_equal'])
    debug_execute(gc.apply, ['circle_property_radius_equal'])

    # prove ∠ad = ∠dk
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])

    # prove ∠kp = ∠px
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])
    debug_execute(gc.apply, ['circle_property_radius_equal'])
    debug_execute(gc.apply, ['circle_property_radius_equal'])
    debug_execute(gc.apply, ['circle_property_radius_equal'])

    # prove ∠lc = ∠ca
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])

    # prove ∠yp = ∠pl
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])
    debug_execute(gc.apply, ['line_property_angle_addition'])
    debug_execute(gc.apply, ['line_property_angle_addition'])
    debug_execute(gc.apply, ['line_property_angle_addition'])
    debug_execute(gc.apply, ['line_property_angle_addition'])

    # prove y // k
    debug_execute(gc.apply, ['equal_angle_determination_algebraic'])
    debug_execute(gc.apply, ['parallel_determination_angle_equal'])

    # prove x // l
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic'])
    debug_execute(gc.apply, ['parallel_determination_angle_equal'])
    debug_execute(gc.apply, ['perpendicular_bisector_determination_center_line_and_common_chord'])
    debug_execute(gc.apply, ['perpendicular_bisector_property_perpendicular_between_line'])

    # prove ∠fp = 2∠ad
    debug_execute(gc.apply, ['perpendicular_between_line_property_multiple_forms'])
    debug_execute(gc.apply, ['perpendicular_between_line_property_angle'])
    debug_execute(gc.apply, ['perpendicular_between_line_property_angle'])
    debug_execute(gc.apply, ['perpendicular_bisector_property_distance_equal'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['triangle_property_angle_sum'])
    debug_execute(gc.apply, ['triangle_property_angle_sum'])
    debug_execute(gc.apply, ['line_property_angle_addition'])
    debug_execute(gc.apply, ['concyclic_between_points_determination_same_circle'])
    debug_execute(gc.apply, ['concyclic_between_points_property_inscribed_angle_sum'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])

    # prove ∠pe = 2∠ca
    debug_execute(gc.apply, ['perpendicular_bisector_property_multiple_forms'])
    debug_execute(gc.apply, ['perpendicular_bisector_property_distance_equal'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['triangle_property_angle_sum'])
    debug_execute(gc.apply, ['triangle_property_angle_sum'])
    debug_execute(gc.apply, ['line_property_angle_addition'])
    debug_execute(gc.apply, ['concyclic_between_points_determination_same_circle'])
    debug_execute(gc.apply, ['concyclic_between_points_property_inscribed_angle_equal'])

    # prove ∠ay = 2∠ad
    debug_execute(gc.apply, ['triangle_property_angle_sum'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.apply, ['parallel_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])

    # prove ∠la = 2∠ca
    debug_execute(gc.apply, ['triangle_property_angle_sum'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])

    # prove ∠xy = 2∠ad + 2∠ca
    debug_execute(gc.apply, ['line_property_angle_addition'])
    debug_execute(gc.apply, ['parallel_property_multiple_forms'])
    debug_execute(gc.apply, ['parallel_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])

    # prove ∠ef + ∠xy = 180° (T on Φ)
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['triangle_property_angle_sum'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_multiple_forms'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_multiple_forms'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle'])
    debug_execute(gc.apply, ['circumcircle_of_triangle_property_point_on_circle'])
    debug_execute(gc.apply, ['concyclic_between_points_determination_inscribed_angle_sum'])
    debug_execute(gc.apply, ['point_on_circle_determination_concyclic'])

    # prove m ⊥ c
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_determination_sss'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_determination_asa'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_multiple_forms'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_multiple_forms'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])

    # prove n ⊥ d
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_determination_sss'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_determination_asa'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_multiple_forms'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_multiple_forms'])
    debug_execute(gc.apply, ['mirror_congruent_triangle_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])

    # prove i // c
    debug_execute(gc.apply, ['orthocenter_of_triangle_property_multiple_forms'])
    debug_execute(gc.apply, ['orthocenter_of_triangle_property_perpendicular'])
    debug_execute(gc.apply, ['perpendicular_between_line_property_angle'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic'])
    debug_execute(gc.apply, ['parallel_determination_angle_equal'])

    # prove ∠xi = ∠ia
    debug_execute(gc.apply, ['parallel_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])
    debug_execute(gc.apply, ['line_property_angle_addition'])
    debug_execute(gc.apply, ['parallel_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic'])
    debug_execute(gc.apply, ['angle_bisector_determination_angle_equal'])

    # prove j // d
    debug_execute(gc.apply, ['orthocenter_of_triangle_property_multiple_forms'])
    debug_execute(gc.apply, ['orthocenter_of_triangle_property_perpendicular'])
    debug_execute(gc.apply, ['perpendicular_between_line_property_angle'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic'])
    debug_execute(gc.apply, ['parallel_determination_angle_equal'])

    # prove ∠aj = ∠jy
    debug_execute(gc.apply, ['parallel_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.apply, ['line_property_angle_addition'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic'])
    debug_execute(gc.apply, ['angle_bisector_determination_angle_equal'])

    # prove ∠yt = ∠tx
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['incenter_of_triangle_determination_angle_bisector'])
    debug_execute(gc.apply, ['incenter_of_triangle_property_angle_bisector'])
    debug_execute(gc.apply, ['angle_bisector_property_equal_angle'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])

    # prove t // p
    debug_execute(gc.apply, ['line_property_angle_addition'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['triangle_property_angle_sum'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.apply, ['equal_angle_determination_algebraic'])
    debug_execute(gc.apply, ['parallel_determination_angle_equal'])
    debug_execute(gc.apply, ['parallel_property_multiple_forms'])

    # prove b ⊥ p
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['triangle_determination'])
    debug_execute(gc.apply, ['circle_property_radius_equal'])
    debug_execute(gc.apply, ['circle_property_radius_equal'])
    debug_execute(gc.apply, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.apply, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.apply, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])
    debug_execute(gc.apply, ['arc_property_central_angle_and_inscribed_angle'])
    debug_execute(gc.apply, ['arc_property_central_angle_and_inscribed_angle'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.apply, ['triangle_property_angle_sum'])
    debug_execute(gc.apply, ['triangle_property_angle_sum'])
    debug_execute(gc.apply, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.apply, ['parallel_property_angle_equal'])
    debug_execute(gc.apply, ['equal_angle_property_algebraic'])

    # prove t ⊥ p
    debug_execute(gc.apply, ['perpendicular_between_line_determination_angle'])
    debug_execute(gc.apply, ['perpendicular_between_line_property_multiple_forms'])
    debug_execute(gc.apply, ['tangent_between_line_and_circle_determination_perpendicular'])

    end_time = time.time()

    if not timing:
        gc.show_gc()
        print(gc.get_gc())
        gc.draw_sg(save_path='../outputs/', file_format='png')

    return gc, end_time - start_time


def backward_solving_automatic(timing=False):
    """theorems: 204"""
    gc, _ = construction(timing)

    start_time = time.time()

    debug_execute(gc.decompose, ['tangent_between_line_and_circle_determination_perpendicular'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_multiple_forms'])
    debug_execute(gc.decompose, ['perpendicular_between_line_determination_angle'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal'])
    debug_execute(gc.decompose, ['parallel_property_multiple_forms'])
    debug_execute(gc.decompose, ['parallel_determination_angle_equal'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['line_property_angle_addition'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['angle_bisector_property_equal_angle'])
    debug_execute(gc.decompose, ['incenter_of_triangle_property_angle_bisector'])
    debug_execute(gc.decompose, ['incenter_of_triangle_determination_angle_bisector'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['angle_bisector_determination_angle_equal'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic'])
    debug_execute(gc.decompose, ['line_property_angle_addition'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal'])
    debug_execute(gc.decompose, ['parallel_determination_angle_equal'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_angle'])
    debug_execute(gc.decompose, ['orthocenter_of_triangle_property_perpendicular'])
    debug_execute(gc.decompose, ['orthocenter_of_triangle_property_multiple_forms'])
    debug_execute(gc.decompose, ['angle_bisector_determination_angle_equal'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic'])
    debug_execute(gc.decompose, ['line_property_angle_addition'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal'])
    debug_execute(gc.decompose, ['parallel_determination_angle_equal'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_angle'])
    debug_execute(gc.decompose, ['orthocenter_of_triangle_property_perpendicular'])
    debug_execute(gc.decompose, ['orthocenter_of_triangle_property_multiple_forms'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_angle_equal'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_multiple_forms'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_multiple_forms'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_determination_asa'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_angle_equal'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_determination_sss'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_angle_equal'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_multiple_forms'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_multiple_forms'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_determination_asa'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_property_angle_equal'])
    debug_execute(gc.decompose, ['mirror_congruent_triangle_determination_sss'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.decompose, ['point_on_circle_determination_concyclic'])
    debug_execute(gc.decompose, ['concyclic_between_points_determination_inscribed_angle_sum'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_multiple_forms'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_multiple_forms'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal'])
    debug_execute(gc.decompose, ['parallel_property_multiple_forms'])
    debug_execute(gc.decompose, ['line_property_angle_addition'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal'])
    debug_execute(gc.decompose, ['concyclic_between_points_property_inscribed_angle_equal'])
    debug_execute(gc.decompose, ['concyclic_between_points_determination_same_circle'])
    debug_execute(gc.decompose, ['line_property_angle_addition'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['perpendicular_bisector_property_distance_equal'])
    debug_execute(gc.decompose, ['perpendicular_bisector_property_multiple_forms'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['concyclic_between_points_property_inscribed_angle_sum'])
    debug_execute(gc.decompose, ['concyclic_between_points_determination_same_circle'])
    debug_execute(gc.decompose, ['line_property_angle_addition'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['perpendicular_bisector_property_distance_equal'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_angle'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_angle'])
    debug_execute(gc.decompose, ['perpendicular_between_line_property_multiple_forms'])
    debug_execute(gc.decompose, ['perpendicular_bisector_property_perpendicular_between_line'])
    debug_execute(gc.decompose, ['perpendicular_bisector_determination_center_line_and_common_chord'])
    debug_execute(gc.decompose, ['parallel_determination_angle_equal'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['parallel_determination_angle_equal'])
    debug_execute(gc.decompose, ['equal_angle_determination_algebraic'])
    debug_execute(gc.decompose, ['line_property_angle_addition'])
    debug_execute(gc.decompose, ['line_property_angle_addition'])
    debug_execute(gc.decompose, ['line_property_angle_addition'])
    debug_execute(gc.decompose, ['line_property_angle_addition'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.decompose, ['circle_property_radius_equal'])
    debug_execute(gc.decompose, ['circle_property_radius_equal'])
    debug_execute(gc.decompose, ['circle_property_radius_equal'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.decompose, ['circle_property_radius_equal'])
    debug_execute(gc.decompose, ['circle_property_radius_equal'])
    debug_execute(gc.decompose, ['circle_property_radius_equal'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.decompose, ['circle_property_radius_equal'])
    debug_execute(gc.decompose, ['circle_property_radius_equal'])
    debug_execute(gc.decompose, ['circle_property_radius_equal'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_point_on_circle'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_multiple_forms'])
    debug_execute(gc.decompose, ['circumcircle_of_triangle_property_multiple_forms'])
    debug_execute(gc.decompose, ['circumcenter_of_triangle_property_center_of_circle'])
    debug_execute(gc.decompose, ['arc_property_central_angle_and_inscribed_angle'])
    debug_execute(gc.decompose, ['arc_property_central_angle_and_inscribed_angle'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['parallel_property_angle_equal'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum'])
    debug_execute(gc.decompose, ['triangle_property_angle_sum'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['triangle_determination'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['line_property_adjacent_complementary_angle'])
    debug_execute(gc.decompose, ['equal_angle_property_algebraic'])
    debug_execute(gc.decompose, ['isosceles_triangle_property_angle_equal'])
    debug_execute(gc.decompose, ['isosceles_triangle_determination_distance_equal'])
    debug_execute(gc.decompose, ['equal_distance_point_to_point_determination_algebraic'])
    debug_execute(gc.decompose, ['circle_property_radius_equal'])
    debug_execute(gc.decompose, ['circle_property_radius_equal'])
    debug_execute(gc.decompose, ['triangle_determination'])

    end_time = time.time()

    if not timing:
        gc.show_gc()
        print(gc.get_gc())
        gc.draw_sg(save_path='../outputs/', file_format='png')

    return gc, end_time - start_time


def test(repeat=5, timeout=5400):
    """timeout set 1.5h (IMO: solve 6 problems in 9h)."""
    log = []

    timing_list = []
    for i in range(repeat):
        print(f'test construction ({i + 1}/{repeat})...')
        _, timing = construction(timing=True)
        timing_list.append(timing)
    log.append(f'construction: {round(sum(timing_list) / len(timing_list), 3)}s')
    print('\n'.join(log))
    print()

    timing_list = []
    for i in range(repeat):
        print(f'test forward solving (interactive) ({i + 1}/{repeat})...')
        _, timing = forward_solving_interactive(timing=True)
        timing_list.append(timing)
    log.append(f'forward solving (interactive): {round(sum(timing_list) / len(timing_list), 3)}s')
    print('\n'.join(log))
    print()

    timing_list = []
    for i in range(repeat):
        print(f'test backward solving (interactive) ({i + 1}/{repeat})...')
        _, timing = backward_solving_interactive(timing=True)
        timing_list.append(timing)
    log.append(f'backward solving (interactive): {round(sum(timing_list) / len(timing_list), 3)}s')
    print('\n'.join(log))
    print()

    timing_list = []
    solved = True
    for i in range(repeat):
        print(f'test forward solving (automatic) ({i + 1}/{repeat})...')
        try:
            _, timing = func_timeout(
                timeout=timeout,
                func=forward_solving_automatic,
                args=(True,)
            )
            timing_list.append(timing)
        except FunctionTimedOut:
            solved = False
            log.append(f'forward solving (automatic): >{timeout}s')
            break
    if solved:
        log.append(f'forward solving (automatic): {round(sum(timing_list) / len(timing_list), 3)}s')
    print('\n'.join(log))
    print()

    timing_list = []
    solved = True
    for i in range(repeat):
        print(f'test backward solving (automatic) ({i + 1}/{repeat})...')
        try:
            _, timing = func_timeout(
                timeout=timeout,
                func=backward_solving_automatic,
                args=(True,)
            )
            timing_list.append(timing)
        except FunctionTimedOut:
            solved = False
            log.append(f'backward solving (automatic): >{timeout}s')
            break
    if solved:
        log.append(f'backward solving (automatic): {round(sum(timing_list) / len(timing_list), 3)}s')
    print('\n'.join(log))
    print()

    with open('../outputs/timing.txt', 'w', encoding="utf-8") as f:
        f.write('\n'.join(log))


if __name__ == '__main__':
    test()
